server {
    listen 80;
    server_name ~^(?<tenant>[^.]+)\..*$;

    root /var/www/html/public;
    index index.php;

    add_header X-Tenant $tenant;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param HTTP_X_TENANT_SUBDOMAIN $tenant;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
